from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path
from typing import Any


PROJECT_ROOT = Path(__file__).resolve().parents[1]
GENERATED_DIR = PROJECT_ROOT / "frontend" / "src" / "generated"

if str(PROJECT_ROOT) not in sys.path:
    sys.path.insert(0, str(PROJECT_ROOT))

from scripts.export_openapi import openapi_schema, write_openapi_schema  # noqa: E402


def ts_string(value: str) -> str:
    return json.dumps(value)


def schema_ref_name(ref: str) -> str:
    prefix = "#/components/schemas/"
    if not ref.startswith(prefix):
        return "unknown"

    return ref.removeprefix(prefix)


def ts_type(schema: dict[str, Any]) -> str:
    if "$ref" in schema:
        return f"components[\"schemas\"][\"{schema_ref_name(schema['$ref'])}\"]"

    if "anyOf" in schema:
        return " | ".join(ts_type(option) for option in schema["anyOf"])

    if "oneOf" in schema:
        return " | ".join(ts_type(option) for option in schema["oneOf"])

    if "allOf" in schema:
        return " & ".join(ts_type(option) for option in schema["allOf"])

    if "enum" in schema:
        return " | ".join(ts_type({"const": value}) for value in schema["enum"])

    if "const" in schema:
        value = schema["const"]
        if value is None:
            return "null"
        if isinstance(value, str):
            return ts_string(value)
        if isinstance(value, bool):
            return "true" if value else "false"
        return json.dumps(value)

    schema_type = schema.get("type")
    if isinstance(schema_type, list):
        return " | ".join(ts_type({"type": option}) for option in schema_type)

    if schema_type == "null":
        return "null"

    if schema_type == "string":
        return "string"

    if schema_type in {"integer", "number"}:
        return "number"

    if schema_type == "boolean":
        return "boolean"

    if schema_type == "array":
        return f"Array<{ts_type(schema.get('items', {}))}>"

    if schema_type == "object" or "properties" in schema:
        properties = schema.get("properties", {})
        if properties:
            required = set(schema.get("required", []))
            lines = ["{"]
            for name, property_schema in sorted(properties.items()):
                optional = "" if name in required else "?"
                lines.append(
                    f"      {json.dumps(name)}{optional}: {ts_type(property_schema)};"
                )
            lines.append("    }")
            return "\n".join(lines)

        additional = schema.get("additionalProperties")
        if isinstance(additional, dict):
            return f"Record<string, {ts_type(additional)}>"

        return "Record<string, unknown>"

    return "unknown"


def render_api_types(schema: dict[str, Any]) -> str:
    schemas = schema.get("components", {}).get("schemas", {})
    lines = [
        "/* eslint-disable */",
        "// Generated by scripts/generate_api_types.py. Do not edit by hand.",
        "",
        "export type components = {",
        "  schemas: {",
    ]
    for name, schema_value in sorted(schemas.items()):
        lines.append(f"    {json.dumps(name)}: {ts_type(schema_value)};")
    lines.extend(
        [
            "  };",
            "};",
            "",
        ]
    )
    return "\n".join(lines)


def write_api_types(path: Path, schema: dict[str, Any]) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(render_api_types(schema), encoding="utf-8")


def generate_contracts(output_dir: Path = GENERATED_DIR) -> None:
    schema = openapi_schema()
    write_openapi_schema(output_dir / "openapi.json")
    write_api_types(output_dir / "api-types.ts", schema)


def main() -> int:
    parser = argparse.ArgumentParser(
        description="Generate frontend API contract types from OpenAPI.",
    )
    parser.add_argument(
        "output_dir",
        nargs="?",
        default=GENERATED_DIR,
        type=Path,
    )
    args = parser.parse_args()

    generate_contracts(args.output_dir)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
